export const ipcEvents = {
  BROWSE_FILES: "BROWSE_FILES",
  BROWSE_FILES_RESULT: "BROWSE_FILES_RESULT",
  DELETE_FILE: "DELETE_FILE",
  DELETE_FILE_RESULT: "DELETE_FILE_RESULT",
  PROCESS_FILES: "PROCESS_FILES",
  PROCESS_FILES_RESULT: "PROCESS_FILES_SUCCESS"
};
