export const ipcEvents = {
  BROWSE_FILES: "BROWSE_FILES",
  BROWSE_FILES_RESULT: "BROWSE_FILES_RESULT",
  DELETE_FILE: "DELETE_FILE",
  DELETE_FILE_RESULT: "DELETE_FILE_RESULT",
  PROCESS_FILES: "PROCESS_FILES",
  PROCESS_FILES_RESULT: "PROCESS_FILES_SUCCESS",
  LOAD_FILE: "LOAD_FILE",
  LOAD_FILE_RESULT: "LOAD_FILE_RESULT",
  LOAD_FILE_ERROR: "LOAD_FILE_ERROR",
  COVERAGE_PERCENT: "COVERAGE_PERCENT",
  COVERAGE_PERCENT_RESULT: "COVERAGE_PERCENT_RESULT"
};

export const workerActions = {
  COVERAGE_PERCENT: "COVERAGE_PERCENT",
  COVERAGE_POINT: "COVERAGE_POINT",
  RANDOM_POINTS: "RANDOM_POINTS"
};
